"""Build a self-hosted subset of the Tabler icon font containing only the icons the site uses.

Scans src/ for `ti-<name>` classes, subsets Tabler Icons (pinned version) to those glyphs, and writes
  public/fonts/tabler-subset.woff2   (a few KB instead of ~780 KB for the full set)
  src/styles/icons.css               (@font-face + .ti base class + only the used icon classes)
Re-run after using a new icon:  python scripts/build-icons.py   (needs: pip install fonttools brotli)
"""
import io
import re
import urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

VERSION = "2.47.0"
BASE = f"https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@{VERSION}"
ROOT = Path(__file__).resolve().parent.parent


def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"}), timeout=60).read()


def main():
    used = set()
    for f in (ROOT / "src").rglob("*"):
        if f.suffix in {".astro", ".ts", ".js", ".md", ".mjs"}:
            used |= set(re.findall(r"\bti-([a-z0-9]+(?:-[a-z0-9]+)*)", f.read_text(encoding="utf-8", errors="ignore")))
    css = fetch(f"{BASE}/tabler-icons.min.css").decode("utf-8")
    codes = dict(re.findall(r'\.ti-([a-z0-9-]+):before\{content:"\\([0-9a-f]+)"\}', css))
    found = {n: codes[n] for n in sorted(used) if n in codes}
    missing = sorted(used - set(found))

    font = TTFont(io.BytesIO(fetch(f"{BASE}/fonts/tabler-icons.woff2?v{VERSION}")))
    # Icons are addressed by codepoint (CSS `content`), not ligatures; Tabler's ligature table also
    # fails to parse in fontTools, so drop the OpenType layout tables before subsetting.
    for tag in ("GSUB", "GPOS", "GDEF"):
        if tag in font:
            del font[tag]
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = []
    opts.name_IDs = []
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=[int(c, 16) for c in found.values()])
    sub.subset(font)
    out = ROOT / "public" / "fonts" / "tabler-subset.woff2"
    out.parent.mkdir(parents=True, exist_ok=True)
    font.flavor = "woff2"
    font.save(out)

    rules = "\n".join(f'.ti-{n}:before {{ content: "\\{c}"; }}' for n, c in found.items())
    (ROOT / "src" / "styles" / "icons.css").write_text(
        f"""/* Generated by scripts/build-icons.py — Tabler Icons {VERSION} (MIT), subset to the {len(found)} icons this site uses. */
@font-face {{
  font-family: 'tabler-icons';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url('/fonts/tabler-subset.woff2') format('woff2');
}}
.ti {{
  font-family: 'tabler-icons' !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}}
{rules}
""",
        encoding="utf-8",
    )
    print(f"{len(found)} icons -> {out.name} ({out.stat().st_size // 1024} KB); not icons/unknown: {', '.join(missing) or 'none'}")


if __name__ == "__main__":
    main()
